apiVersion: trust.cert-manager.io/v1alpha1
kind: Bundle
metadata:
  name: kubecrash
spec:
  sources:
  - secret:
      name: "root-secret"
      key: "ca.crt"
  target:
    configMap:
      key: "cert.pem"
