---
apiVersion: v1
kind: ConfigMap
metadata:
  name: oauth2proxy
data:
  "oauth2-proxy.cfg": |
    http_address = "0.0.0.0:4180"
    redirect_url = "http://localhost:30001/oauth2/callback"
    upstreams = [
     "http://127.0.0.1:4242/"
    ]
    pass_user_headers = true
    email_domains = [
      "jetstack.io"
    ]
    client_id = "oauth2proxy"
    client_secret = "ZXhhbXBsZS1hcHAtc2VjcmV0"
    cookie_name = "_oauth2_proxy"
    cookie_secret = "sadfghfjhgkhgfds"
    cookie_secure = false
    provider = "oidc"
    oidc_issuer_url = "http://dex.default.svc.cluster.local:30000/dex"
    provider_display_name = "Corporate CO SSO"
---
apiVersion: v1
kind: Service
metadata:
  name: oauth2proxy
spec:
  type: NodePort
  selector:
    app: oauth2proxy
  ports:
  - protocol: TCP
    port: 4180
    nodePort: 30001
    targetPort: 4180
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: oauth2proxy
  labels:
    app: oauth2proxy
spec:
  selector:
    matchLabels:
      app: oauth2proxy
  template:
    metadata:
      labels:
        app: oauth2proxy
    spec:
      volumes:
        - name: cfg
          configMap:
            name: oauth2proxy
            defaultMode: 0444
        - name: ca
          configMap:
            name: kubecrash
            defaultMode: 0444
        - name: tls
          csi:
            readOnly: true
            driver: csi.cert-manager.io
            volumeAttributes:
              csi.cert-manager.io/issuer-name: trust-domain-root
              csi.cert-manager.io/issuer-kind: ClusterIssuer
              csi.cert-manager.io/dns-names: supersecureapp.default.svc.cluster.local
      containers:
        - name: ghostunnel
          image: ghostunnel/ghostunnel
          args:
            - "client"
            - "--listen=127.0.0.1:4242"
            - "--target=supersecureapp.default.svc.cluster.local:8080"
            - "--cert=/tls/tls.crt"
            - "--key=/tls/tls.key"
          volumeMounts:
            - mountPath: /cfg
              name: cfg
            - mountPath: /etc/ssl/certs
              name: ca
            - mountPath: /tls
              name: tls
              readOnly: true
        - name: oauth2proxy
          image: quay.io/oauth2-proxy/oauth2-proxy:v7.2.1
          args:
            - "--config=/cfg/oauth2-proxy.cfg"
          volumeMounts:
            - mountPath: /cfg
              name: cfg
          
