---
apiVersion: v1
kind: ConfigMap
metadata:
  name: dex-config
data:
  dex.yaml: |
    issuer: http://dex.default.svc.cluster.local:30000/dex
    storage:
      type: memory
    web:
      http: 0.0.0.0:30000
    logger:
      level: debug
      format: text
    staticClients:
      - id: oauth2proxy
        redirectURIs:
          - 'http://localhost:30001/oauth2/callback'
        name: 'Corporate Co SSO'
        secret: 'ZXhhbXBsZS1hcHAtc2VjcmV0'
    connectors:
      - type: ldap
        id: ldap
        name: LDAP
        config:
          host: 'auth-provider.default.svc.cluster.local:3893'
          insecureNoSSL: true
          bindDN: admin,dc=jetstack,dc=io
          bindPW: password
          usernamePrompt: Company Username
          userSearch:
            baseDN: dc=jetstack,dc=io
            username: uid
            idAttr: uid
            emailAttr: mail
            nameAttr: cn
          groupSearch:
            baseDN: dc=jetstack,dc=io
            userMatchers:
              - userAttr: uid
                groupAttr: ou
            nameAttr: cn
---
apiVersion: v1
kind: Service
metadata:
  name: dex
spec:
  type: NodePort
  selector:
    app: dex
  ports:
  - port: 30000
    targetPort: 30000
    nodePort: 30000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dex
spec:
  selector:
    matchLabels:
      app: dex
  template:
    metadata:
      labels:
        app: dex
    spec:
      containers:
      - name: dex
        image: dexidp/dex
        command:
          - "dex"
        args:
        - "serve"
        - "/app/config/dex.yaml"
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 30000
        volumeMounts:
        - name: dex-config
          mountPath: /app/config
      volumes:
      - name: dex-config
        configMap:
          name: dex-config
