apiVersion: v1
kind: Service
metadata:
  name: supersecureapp
spec:
  type: NodePort
  selector:
    app: supersecureapp
  ports:
  - protocol: TCP
    port: 8080
    nodePort: 30002
    targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: supersecureapp
  labels:
    app: supersecureapp
spec:
  selector:
    matchLabels:
      app: supersecureapp
  template:
    metadata:
      labels:
        app: supersecureapp
    spec:
      volumes:
        - name: ca
          configMap:
            name: kubecrash
            defaultMode: 0444
        - name: tls
          csi:
            readOnly: true
            driver: csi.cert-manager.io
            volumeAttributes:
              csi.cert-manager.io/issuer-name: trust-domain-root
              csi.cert-manager.io/issuer-kind: ClusterIssuer
              csi.cert-manager.io/dns-names: supersecureapp.default.svc.cluster.local
      containers:
        - name: supersecureapp
          image: kubecrash
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - mountPath: /etc/ssl
              name: ca
            - mountPath: /tls
              name: tls
              readOnly: true

